name: dep_analyzer
description: A command-line tool to analyze a DEP csv file
version: 1.0.0
repository: https://github.com/GuilhermeAlecrim7K/dep-analyzer

environment:
  sdk: ^3.0.0

dev_dependencies:
  lint: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.1
  http: ^1.0.0
